### PR TITLE
Add model for ragged batching unit test

### PR DESCRIPTION
**Pull request by kpedro88**
These data files are needed for the new unit test for ragged batching.

### CODE REVIEW

**Comment by kpedro88** [comment]
test parameters
* pull_requests = https://github.com/cms-sw/cmsdist/pull/8324, https://github.com/cms-sw/cmssw/pull/40814, https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/2, https://github.com/cms-data/RecoEcal-EgammaClusterProducers/pull/3

**Comment by kpedro88** [comment]
please test

**Comment by makortel** [comment]
+heterogeneous

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
+1
- New datafiles added

**Pull request merged**
