### PR TITLE
add graph attention network

### PR DESCRIPTION
**Pull request by kpedro88**

### CODE REVIEW

**Comment by smuzaffar** [comment]
ping bot

**Comment by smuzaffar** [comment]
only new files. merging it to get it in Ibs.

**Comment by mrodozov** [comment]
execute permissions were missing

**Comment by smuzaffar** [comment]
> execute permissions were missing

where?

**Comment by smuzaffar** [comment]
ah ok
```
/data/sdt/cms-bot/create-new-data-pr.py: Permission denied
```

**Pull request merged**
