### PR TITLE
[TEST] specify wrong checksum

### PR DESCRIPTION
**Pull request by kpedro88**
This is a test PR to ensure that the unit test added in https://github.com/cms-sw/cmssw/pull/43696 triggers as intended on cms-data PRs. **not to be merged**

### CODE REVIEW

**Comment by kpedro88** [comment]
let's wait to test until the next IB is available

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@kpedro88 ,  unit test for version check passed but looks like the [cfg_versioncheck](https://github.com/cms-sw/cmssw/blob/master/HeterogeneousCore/SonicTriton/scripts/cmsTritonConfigTool#L326-L341) function is only checking the top level files. You need to recursively check all the sub-directories.

Can you please add some print statements about which config files it has processed?

**Comment by kpedro88** [comment]
@smuzaffar it was actually an issue related to symbolic links. I will fix this (and add an option for verbose printouts as requested) in https://github.com/cms-sw/cmssw/pull/43814 (which already includes other various bug fixes). We can leave this PR open to test the fixed script once it's merged.

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
Test works! Output, for the record:
```
 ===== Test "TestHeterogeneousCoreSonicTritonVersionCheck" ====
Traceback (most recent call last):
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_1_X_2024-02-12-1100/bin/el8_amd64_gcc12/cmsTritonConfigTool", line 461, in <module>
    args.func(args)
  File "/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_1_X_2024-02-12-1100/bin/el8_amd64_gcc12/cmsTritonConfigTool", line 357, in cfg_versioncheck
    raise RuntimeError("\n".join(msg+instr))
RuntimeError: 
The following files have incorrect checksum(s), indicating existing model file(s) have been changed, which violates policy:
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_1_X_2024-02-12-1100/external/el8_amd64_gcc12/data/HeterogeneousCore/SonicTriton/data/models/ragged_io/config.pbtxt

To override incorrect checksums, run the following command (and provide a justification in your PR):
/data/cmsbld/jenkins/workspace/ib-run-pr-tests/CMSSW_14_1_X_2024-02-12-1100/bin/el8_amd64_gcc12/cmsTritonConfigTool versioncheck --update --force

---> test TestHeterogeneousCoreSonicTritonVersionCheck had ERRORS
TestTime:12
^^^^ End Test TestHeterogeneousCoreSonicTritonVersionCheck ^^^^
```

**Comment by makortel** [comment]
Thanks Kevin

**Pull request closed without merging**
