### PR TITLE
add model checksums

### PR DESCRIPTION
**Pull request by kpedro88**
for https://github.com/cms-sw/cmssw/issues/43695

NB:  default field values omitted when printing with cmsTritonConfigTool

### CODE REVIEW

**Comment by kpedro88** [comment]
please test

**Comment by kpedro88** [comment]
[@cms-sw/heterogeneous-l2](https://github.com/orgs/cms-sw/teams/heterogeneous-l2) please sign so we can move to the next step of the plan in https://github.com/cms-sw/cmssw/issues/43695

**Comment by makortel** [comment]
+heterogeneous

**Comment by smuzaffar** [comment]
+externals

**Comment by rappoccio** [comment]
+1

**Pull request merged**
